# Generated by Django 3.1rc1 on 2020-09-10 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='subtitle',
            field=models.CharField(default="Hello! I'M Sarthak Singh.", max_length=20),
        ),
        migrations.AddField(
            model_name='about',
            name='title',
            field=models.CharField(default='About Me', max_length=15),
        ),
    ]
