# Generated by Django 3.1rc1 on 2020-09-10 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_auto_20200910_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='subtitle',
            field=models.CharField(default="Hello! I'M Sarthak Singh.", max_length=50),
        ),
        migrations.AlterField(
            model_name='about',
            name='title',
            field=models.CharField(default='About Me', max_length=50),
        ),
    ]
