# Generated by Django 3.1rc1 on 2020-09-10 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_auto_20200910_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='subtitle',
        ),
        migrations.AddField(
            model_name='about',
            name='subtitle_normal',
            field=models.CharField(default='Hello!', max_length=30),
        ),
        migrations.AddField(
            model_name='about',
            name='subtitle_styled',
            field=models.CharField(default="I'M Sarthak Singh.", max_length=30),
        ),
    ]
