# Generated by Django 3.1rc1 on 2020-09-10 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_skill_skill_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='social',
            name='name',
            field=models.CharField(default='name here', max_length=50),
        ),
    ]
