# Generated by Django 3.1rc1 on 2020-09-11 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_auto_20200910_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_image', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
    ]
