# Generated by Django 3.1rc1 on 2020-09-11 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0009_auto_20200911_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=100)),
                ('platform', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
