# Generated by Django 3.1rc1 on 2020-09-11 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0011_project_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='link',
            new_name='button_link',
        ),
        migrations.AddField(
            model_name='project',
            name='button_text',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
