# Generated by Django 3.1rc1 on 2020-09-11 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0012_auto_20200911_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='Port_Column',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Port_Filter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('button_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Port_Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='resume.port_column')),
                ('filter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='resume.port_filter')),
            ],
        ),
        migrations.CreateModel(
            name='Port_Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vid_link', models.URLField(blank=True)),
                ('vid_title', models.CharField(max_length=40)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.port_item')),
            ],
        ),
        migrations.CreateModel(
            name='Port_Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('position', models.FloatField()),
                ('caption', models.TextField(blank=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.port_item')),
            ],
        ),
    ]
