# Generated by Django 3.1rc1 on 2020-09-11 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0013_port_column_port_filter_port_image_port_item_port_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='port_column',
            name='number',
            field=models.DecimalField(decimal_places=0, max_digits=1),
        ),
    ]
