# Generated by Django 3.1rc1 on 2020-09-11 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0014_auto_20200912_0016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='port_video',
            name='parent',
        ),
        migrations.AddField(
            model_name='port_item',
            name='caption',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='port_item',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='port_item',
            name='position',
            field=models.FloatField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='port_item',
            name='vid_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='port_item',
            name='vid_title',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Port_Image',
        ),
        migrations.DeleteModel(
            name='Port_Video',
        ),
    ]
