# Generated by Django 3.1rc1 on 2020-09-11 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0016_auto_20200912_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='port_item',
            name='position',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
