# Generated by Django 3.1rc1 on 2020-09-11 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0017_auto_20200912_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='port_item',
            name='position',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=9999, null=True),
        ),
    ]
