# Generated by Django 3.1rc1 on 2020-09-11 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0019_social_about_include'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='link',
            field=models.URLField(),
        ),
    ]
