# Generated by Django 3.1rc1 on 2020-09-12 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0020_auto_20200912_0149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.CharField(max_length=20)),
                ('head', models.CharField(max_length=50)),
                ('detail', models.TextField()),
            ],
        ),
    ]
