# Generated by Django 3.1rc1 on 2020-09-12 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0021_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='logo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='skill_category',
            name='logo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='social',
            name='logo',
            field=models.CharField(max_length=50),
        ),
    ]
